version: '3.6'
services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=product
      - POSTGRES_PASSWORD=product
    ports:
      - 5432:5432
  axon-server:
    image: axoniq/axonserver
    volumes:
      - ./axon/data:/data
      - ./axon/eventdata:/eventdata
      - ./axon/config:/config
    ports:
      - 8024:8024
      - 8124:8124
